package com.haruUp.global.schema

import org.flywaydb.core.Flyway
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.DisplayName
import org.junit.jupiter.api.Tag
import org.junit.jupiter.api.Test
import java.sql.DriverManager
import java.util.Properties

/**
 * Flyway 마이그레이션을 실제 PostgreSQL에 적용해 검증한다.
 *
 * 실행 중인 로컬 DB가 필요해 평소 테스트에서는 제외된다.
 *   docker compose up -d postgres
 *   ./gradlew flywayVerify
 *
 * 검증 대상은 두 가지 시나리오다.
 * 1. 빈 DB(신규 개발자 로컬)  : V1부터 전부 실행되어 스키마가 만들어진다
 * 2. 기존 DB(운영/개발)       : baseline으로 V1을 건너뛰고 V2부터 실행된다
 *
 * 각 시나리오는 임시 스키마에서 돌리고 끝나면 지운다. 기존 데이터는 건드리지 않는다.
 */
@Tag("flyway-verify")
class FlywayMigrationTest {

    private val env = Properties().apply {
        FlywayMigrationTest::class.java.classLoader.getResourceAsStream("env.properties")!!.use { load(it) }
    }

    private val url = "jdbc:postgresql://${env.getProperty("POSTGRES_HOST")}:" +
        "${env.getProperty("POSTGRES_PORT")}/${env.getProperty("POSTGRES_DB")}"
    private val user = env.getProperty("POSTGRES_USER")
    private val password = env.getProperty("POSTGRES_PASSWORD")

    private fun flywayFor(schema: String): Flyway =
        Flyway.configure()
            .dataSource(url, user, password)
            .schemas(schema)
            .defaultSchema(schema)
            .locations("classpath:db/migration")
            .baselineOnMigrate(true)
            .baselineVersion("1")
            .load()

    private fun <T> withTempSchema(name: String, block: (java.sql.Connection) -> T): T {
        DriverManager.getConnection(url, user, password).use { conn ->
            conn.createStatement().use { it.execute("DROP SCHEMA IF EXISTS $name CASCADE") }
            try {
                return block(conn)
            } finally {
                conn.createStatement().use { it.execute("DROP SCHEMA IF EXISTS $name CASCADE") }
            }
        }
    }

    private fun columnExists(conn: java.sql.Connection, schema: String, table: String, column: String): Boolean {
        conn.prepareStatement(
            """
            SELECT 1 FROM information_schema.columns
            WHERE table_schema = ? AND table_name = ? AND column_name = ?
            """
        ).use { ps ->
            ps.setString(1, schema)
            ps.setString(2, table)
            ps.setString(3, column)
            ps.executeQuery().use { return it.next() }
        }
    }

    @Test
    @DisplayName("빈 DB에서는 V1부터 전부 실행되어 스키마가 만들어진다")
    fun `빈 DB 전체 마이그레이션`() {
        val schema = "flyway_verify_fresh"

        withTempSchema(schema) { conn ->
            val result = flywayFor(schema).migrate()

            assertEquals(3, result.migrationsExecuted, "V1, V2, V3가 모두 실행되어야 한다")
            assertTrue(columnExists(conn, schema, "member_goal", "user_summary"))
            assertTrue(columnExists(conn, schema, "member_character", "personality"))
            // 스네이크 케이스 네이밍이 실제로 적용됐는지 (createdAt 이 아니라 created_at)
            assertTrue(columnExists(conn, schema, "member_goal", "created_at"))
        }
    }

    @Test
    @DisplayName("기존 DB는 V1을 건너뛰고 V2부터 실행된다")
    fun `기존 DB baseline 후 증분 적용`() {
        val schema = "flyway_verify_existing"

        withTempSchema(schema) { conn ->
            // Flyway 도입 전 상태를 만든다: 신규 컬럼이 없는 기존 스키마
            conn.createStatement().use { st ->
                st.execute("CREATE SCHEMA $schema")
                st.execute(
                    """
                    CREATE TABLE $schema.member_goal (
                        id bigint generated by default as identity primary key,
                        member_id bigint not null,
                        goal_text TEXT not null,
                        conversation_summary TEXT not null,
                        is_active boolean not null,
                        deleted boolean not null
                    )
                    """
                )
                st.execute(
                    """
                    CREATE TABLE $schema.member_character (
                        id bigint generated by default as identity primary key,
                        member_id bigint not null,
                        character_id bigint not null,
                        deleted boolean not null
                    )
                    """
                )
            }

            val result = flywayFor(schema).migrate()

            assertEquals(2, result.migrationsExecuted, "baseline 이후 V2, V3만 실행되어야 한다")
            assertTrue(columnExists(conn, schema, "member_goal", "user_summary"))
            assertTrue(columnExists(conn, schema, "member_character", "personality"))
        }
    }

    @Test
    @DisplayName("두 번 실행해도 아무것도 다시 적용하지 않는다")
    fun `재실행 시 변화 없음`() {
        val schema = "flyway_verify_repeat"

        withTempSchema(schema) {
            flywayFor(schema).migrate()
            val second = flywayFor(schema).migrate()

            assertEquals(0, second.migrationsExecuted, "이미 적용된 마이그레이션은 다시 실행되지 않아야 한다")
        }
    }
}
