-- 기존 스키마 baseline (V1)
--
-- Flyway 도입 시점에 이미 운영/개발 DB에 존재하던 스키마다.
-- 기존 DB 는 baseline-on-migrate 로 이 버전이 적용된 것으로 표시되고 실제로 실행되지 않는다.
-- 실제로 실행되는 곳은 테이블이 하나도 없는 새 DB(신규 개발자 로컬 등)뿐이다.
--
-- JPA 엔티티에서 생성했다: ./gradlew generateSchemaDdl
-- 운영 스키마와 100% 동일하다고 보장할 수 없으므로, 차이를 발견하면 이 파일이 아니라
-- 새 버전(V4, V5...)으로 보정한다. 이미 적용된 마이그레이션은 수정하지 않는다.

create table character (
        deleted boolean not null,
        character_img_ref bigint,
        created_at timestamp(6),
        deleted_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        description varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table files (
        deleted boolean not null,
        created_at timestamp(6),
        deleted_at timestamp(6),
        file_size bigint not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        content_type varchar(255),
        file_path varchar(255),
        original_name varchar(255),
        stored_name varchar(255),
        primary key (id)
    );

    create table interest_embeddings (
        deleted boolean not null,
        is_activated boolean,
        usage_count integer,
        created_at timestamp(6),
        deleted_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        created_source varchar(20),
        level varchar(20) not null check (level in ('MAIN','MIDDLE','SUB')),
        embedding vector(1024),
        name varchar(255) not null,
        parent_id varchar(255),
        full_path text[] not null,
        primary key (id)
    );

    create table job (
        deleted boolean not null,
        created_at timestamp(6),
        deleted_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        job_name varchar(255),
        primary key (id)
    );

    create table job_detail (
        deleted boolean not null,
        created_at timestamp(6),
        deleted_at timestamp(6),
        id bigint generated by default as identity,
        job_id bigint not null,
        updated_at timestamp(6),
        job_detail_name varchar(255),
        primary key (id)
    );

    create table level (
        deleted boolean not null,
        level_number integer not null,
        max_exp integer,
        required_exp integer not null,
        created_at timestamp(6),
        deleted_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        primary key (id)
    );

    create table member (
        deleted boolean not null,
        created_at timestamp(6),
        deleted_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        email varchar(255) not null,
        login_type varchar(255) not null check (login_type in ('COMMON','KAKAO','GOOGLE','APPLE','NAVER')),
        name varchar(255) not null,
        password varchar(255),
        sns_id varchar(255),
        status varchar(255) not null check (status in ('ACTIVE','INACTIVE','SUSPENDED','DELETED')),
        primary key (id)
    );

    create table member_custom_mission (
        deleted boolean not null,
        target_date date not null,
        created_at timestamp(6),
        deleted_at timestamp(6),
        id bigint generated by default as identity,
        member_id bigint not null,
        updated_at timestamp(6),
        mission_content TEXT not null,
        mission_status varchar(255) check (mission_status in ('READY','ACTIVE','POSTPONED','COMPLETED','INACTIVE')),
        type varchar(255) not null check (type in ('CUSTOM','OTHER_INTEREST')),
        primary key (id)
    );

    create table member_goal (
        deleted boolean not null,
        is_active boolean not null,
        created_at timestamp(6),
        deleted_at timestamp(6),
        id bigint generated by default as identity,
        member_id bigint not null,
        updated_at timestamp(6),
        conversation_raw TEXT,
        conversation_summary TEXT not null,
        goal_text TEXT not null,
        primary key (id)
    );

    create table member_interest (
        deleted boolean not null,
        reset_mission_count integer default 0 not null,
        created_at timestamp(6),
        deleted_at timestamp(6),
        id bigint generated by default as identity,
        interest_id bigint not null,
        member_id bigint not null,
        updated_at timestamp(6),
        direct_full_path text[],
        primary key (id)
    );

    create table member_mission (
        deleted boolean not null,
        difficulty integer,
        exp_earned integer not null,
        is_selected boolean not null,
        target_date date not null,
        created_at timestamp(6),
        deleted_at timestamp(6),
        id bigint generated by default as identity,
        member_id bigint not null,
        member_interest_id bigint not null,
        updated_at timestamp(6),
        label_name varchar(100),
        embedding vector(1024),
        mission_content TEXT not null,
        mission_description TEXT,
        mission_status varchar(255) check (mission_status in ('READY','ACTIVE','POSTPONED','COMPLETED','INACTIVE')),
        primary key (id)
    );

    create table member_profile (
        birth_dt timestamp(6),
        id bigint generated by default as identity,
        img_id bigint,
        job_detail_id bigint,
        job_id bigint,
        member_id bigint not null unique,
        nickname varchar(50),
        intro varchar(500),
        gender varchar(255) check (gender in ('MALE','FEMALE','OTHER')),
        primary key (id)
    );

    create table member_character (
        completed_missions integer not null,
        current_exp integer not null,
        current_streak_days integer not null,
        deleted boolean not null,
        failed_missions integer not null,
        last_mission_date date,
        longest_streak_days integer not null,
        total_exp integer not null,
        total_missions integer not null,
        character_id bigint not null,
        created_at timestamp(6),
        deleted_at timestamp(6),
        id bigint generated by default as identity,
        level_id bigint not null,
        member_id bigint not null,
        updated_at timestamp(6),
        primary key (id)
    );

    create table member_mission_reminder (
        deleted boolean not null,
        created_at timestamp(6),
        deleted_at timestamp(6),
        id bigint generated by default as identity,
        member_id bigint not null,
        reminder_dt timestamp(6),
        updated_at timestamp(6),
        primary key (id)
    );

    create table member_setting (
        deleted boolean not null,
        email_enabled boolean not null,
        marketing_consent boolean not null,
        push_enabled boolean not null,
        created_at timestamp(6),
        deleted_at timestamp(6),
        id bigint generated by default as identity,
        member_id bigint not null,
        updated_at timestamp(6),
        theme varchar(255) not null check (theme in ('LIGTH','DARK')),
        primary key (id)
    );

    create table push_device_token (
        deleted boolean not null,
        created_at timestamp(6),
        deleted_at timestamp(6),
        id bigint generated by default as identity,
        member_id bigint not null,
        updated_at timestamp(6),
        platform varchar(20) not null check (platform in ('ANDROID','IOS','WEB','UNKNOWN')),
        device_id varchar(100) not null,
        token varchar(500) not null,
        primary key (id)
    );

    create table ranking_mission_daily (
        birth_dt date,
        deleted boolean not null,
        ranking_date date not null,
        created_at timestamp(6),
        deleted_at timestamp(6),
        id bigint generated by default as identity,
        job_detail_id bigint,
        job_id bigint,
        member_mission_id bigint not null unique,
        updated_at timestamp(6),
        gender varchar(10) check (gender in ('MALE','FEMALE','OTHER')),
        label_name varchar(100),
        interest_full_path TEXT[],
        primary key (id)
    );

    create table refresh_token (
        deleted boolean not null,
        revoked boolean not null,
        created_at timestamp(6),
        deleted_at timestamp(6),
        expires_at timestamp(6) not null,
        id bigint generated by default as identity,
        member_id bigint not null,
        updated_at timestamp(6),
        token varchar(255) not null,
        primary key (id)
    );

    create index idx_level 
       on interest_embeddings (level);

    create index idx_is_activated 
       on interest_embeddings (is_activated);

    create index idx_custom_mission_member_id 
       on member_custom_mission (member_id);

    create index idx_custom_mission_target_date 
       on member_custom_mission (target_date);

    create index idx_member_goal_member_id 
       on member_goal (member_id);

    create index idx_member_goal_is_active 
       on member_goal (is_active);

    create index idx_member_interest_member_id 
       on member_interest (member_id);

    create index idx_member_interest_interest_id 
       on member_interest (interest_id);

    create index idx_member_interest_created_at 
       on member_interest (created_at);

    create index idx_member_mission_member_id 
       on member_mission (member_id);

    create index idx_member_mission_created_at 
       on member_mission (created_at);

    create index idx_member_mission_difficulty 
       on member_mission (difficulty);

    create index idx_ranking_daily_date 
       on ranking_mission_daily (ranking_date);

    create index idx_ranking_daily_filter 
       on ranking_mission_daily (ranking_date, birth_dt, gender, job_id, job_detail_id);
